apiVersion: v1
kind: Pod
metadata:
  name: airbyte-bootloader-{{ randAlphaNum 6 | lower }}
  labels:
  {{ include "airbyte-plural.labels" . | nindent 4 }}
spec:
  serviceAccountName: airbyte-admin
  restartPolicy: Never
  initContainers:
  - name: wait-for-pg
    image: gcr.io/pluralsh/busybox:latest
    imagePullPolicy: IfNotPresent
    command: [ "/bin/sh", "-c", "until nc -zv $DATABASE_HOST 5432 -w1; do echo 'waiting for db'; sleep 1; done" ]
    env:
    - name: DATABASE_HOST
      valueFrom:
        configMapKeyRef:
          name: airbyte-airbyte-env
          key: DATABASE_HOST
  containers:
  - name: airbyte-bootloader-container
    image: {{ printf "%s:%s" .Values.bootloader.image.repository .Values.bootloader.image.tag }}
    imagePullPolicy: IfNotPresent
    env:
    - name: AIRBYTE_VERSION
      valueFrom:
        configMapKeyRef:
          name: airbyte-airbyte-env
          key: AIRBYTE_VERSION
    - name: DATABASE_HOST
      valueFrom:
        configMapKeyRef:
          name: airbyte-airbyte-env
          key: DATABASE_HOST
    - name: DATABASE_PORT
      valueFrom:
        configMapKeyRef:
          name: airbyte-airbyte-env
          key: DATABASE_PORT
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Values.global.database.secretName }}
          key: {{ .Values.global.database.secretValue }}
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          name: airbyte-airbyte-env
          key: DATABASE_URL
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: airbyte-airbyte-secrets
          key: DATABASE_USER