{{ if index $.Values "oidc-config" "enabled" }}
apiVersion: v1
kind: Service
metadata:
  name: oauth-proxy-svc
  labels:
  {{ include "airbyte.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/name: webapp
  ports:
  - port: 80
    targetPort: 4180
    protocol: TCP
    name: http-oauth
{{ end }}

