apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: ingress-nginx aws setup 
  version: 0.1.2
spec:
  dependencies:
  - name: aws-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.1'
    optional: true
  providers:
  - aws
