apiVersion: v2
name: ingress-nginx
description: A helm chart for ingress-nginx
version: 0.1.0
appVersion: 1.7.0
dependencies:
- name: ingress-nginx
  version: 0.1.15
  repository: cm://app.plural.sh/cm/ingress-nginx
  condition: ingress-nginx.enabled
- name: ingress-nginx-private
  version: 0.1.20
  repository: cm://app.plural.sh/cm/ingress-nginx
  condition: ingress-nginx-private.enabled
