apiVersion: v2
appVersion: 0.50.33
dependencies:
- name: airbyte
  repository: file://../../../../airbyte/charts/airbyte
  version: 0.43.22
- condition: postgres.enabled
  name: postgres
  repository: https://pluralsh.github.io/module-library
  version: 0.1.16
- condition: oidc-config.enabled
  name: oidc-config
  repository: https://pluralsh.github.io/module-library
  version: 0.1.6
- condition: test-base.enabled
  name: test-base
  repository: https://pluralsh.github.io/module-library
  version: 0.1.10
description: Unified data integration platform
name: airbyte
type: application
version: 0.4.26
