apiVersion: v2
name: airbyte
description: A helm chart for airbyte
version: 0.1.0
appVersion: 0.50.33
dependencies:
- name: airbyte
  version: 0.4.26
  repository: cm://app.plural.sh/cm/airbyte
  condition: airbyte.enabled
